[package]
name = "bw-generator"
version = "1.0.0"
authors = ["Aleksei Trifonov <avrong@avrong.me>"]
edition = "2018"

[dependencies]
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"
toml = "0.5.6"
rand = "0.7.3"
clap = "2.33.0"
gotham = "0.4.0"
gotham_derive = "0.4.0"